config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :movies, only: [:index, :show, :update]
  post '/mark_as_favorite', to: 'movies#create'
  get '/your_favorite', to: 'movies#favorite'

  resources :reviews, only: [:create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
require 'open-uri'

class Movie < ApplicationRecord
  has_one_attached :avatar, dependent: :destroy
  has_many :reviews, dependent: :destroy

  validates :title, :released_year, :reference_id, presence: true

  scope :search_by_title, ->(query) { where("lower(title) LIKE ?", "%#{query.downcase}%") }

  def avatar_url=(url)
    file = open(url)
    self.avatar.attach(io: file, filename: "#{self.reference_id}.jpg", content_type: file.content_type_parse.first)
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie
  validates :email, :description, :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  DEFAULT_TITLE = 'AVATAR'.freeze

  def index
    query = params[:q] || DEFAULT_TITLE
    cache_key = "movies_#{query}"
    @movies = Rails.cache.fetch(cache_key, expires_in: 10.minute) do
      RapidApiService.new.find_by_title(query)
    end
  end

  def show
    @movie = Movie.includes(:reviews).find(params[:id])
    @rating = @movie.reviews.average(:rating).to_i
    @reviews = @movie.reviews
  end

  def favorite
    @favorite_movies = params[:q] ? Movie.search_by_title(params[:q]) : Movie.all
  end

  def create
    @movie = Movie.new(movie_params)
    @movie.avatar_url = params[:image_url] if params[:image_url]
    if @movie.save
      flash[:success] = "Movie added to your favorite list."
      redirect_to your_favorite_path
    else
      flash[:danger] = "Something went wrong."
    end
  end

  private

  def movie_params
    params.permit(:title, :released_year, :reference_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new(review_params)
    if @review.save
      flash[:success] = "Review added to moive."
      redirect_to movie_path(review_params[:movie_id])
    else
      flash[:danger] = @review.errors.full_messages.join(" ")
      redirect_to movie_path(review_params[:movie_id])
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :description, :movie_id, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def image_url(movie)
    if movie.is_a?(ActiveRecord::Base)

    else
      movie.dig('image', 'url') || no_image_url
    end
  end

  def get_reference_id(movie)
    movie["id"].split("/")[2]
  end

  def no_image_url
    'https://via.placeholder.com/450x300'
  end
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Cinema Era</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Home", movies_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
      <%= link_to "Favorite Movies", your_favorite_path, class: "nav-link"%>
      </li>
    </ul>
  </div>

  <%= form_tag request.path, method: :get, class: "form-inline" do %>
    <%= text_field_tag :q, params[:q], placeholder: "Search...", class_name: "form-control mr-sm-2" %>
    <%= submit_tag "Search", class: "btn btn-outline-success my-2 my-sm-0" %>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CinemaEra</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "alert alert-#{name}" %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/movies/favorite.html.erb
<div class="container my-5">
  <div class="row">
    <% if @favorite_movies.any? %>
      <% @favorite_movies.each do |movie| %>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <%= image_tag(movie.avatar, class: "card-img-top", height: 450, width: 300) %>
            <div class="card-body">
            <div class="d-flex justify-content-between align-items-center">
              <h5 class="card-title"><%= movie.title%></h5>
              <%= link_to "show",  movie_path(movie.id), class: "btn btn-sm btn-outline-secondary"  %>
              </div>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">Release year: <%= movie.released_year%></small>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <%else%>
      <p>Sorry, Couldnt find any result for your query.</p>
    <%end%>
  </div>
</div>

app/views/movies/index.html.erb
<div class="container my-5">
  <h1>Welcome to our Movie Website!</h1>
  <p>Here are some of our featured movies:</p>
  <div class="row">
    <% if @movies.any? %>
      <% @movies.each do |movie| %>
        <div class="col-md-4">
          <div class="card mb-4 box-shadow">
            <img class="card-img-top" src="<%= image_url(movie) %>" alt="Movie poster" width="300" height="450">
            <div class="card-body">
              <h5 class="card-title"><%= movie["title"]%></h5>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">Release year: <%= movie['year']%></small>
                <%= form_tag mark_as_favorite_path, method: :post do %>
                  <%= hidden_field_tag :title, movie["title"] %>
                  <%= hidden_field_tag :released_year, movie["year"] %>
                  <%= hidden_field_tag :reference_id, get_reference_id(movie) %>
                  <%= hidden_field_tag :image_url, image_url(movie) %>
                  <%= submit_tag "Mark it favorite", class: "btn btn-sm btn-outline-secondary" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <%else%>
      <p>Sorry, Couldnt find any result for your query.</p>
    <%end%>
  </div>
</div>

app/views/movies/show.html.erb
<div class="container my-5">
  <div class="row">
    <% if @movie %>
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
            <%= image_tag(@movie.avatar, class: "card-img-top", height: 450, width: 300) %>
            <div class="card-body">
              <h5 class="card-title"><%= @movie.title%></h5>
              <div class="d-flex justify-content-between align-items-center">
                <small class="text-muted">Release year: <%= @movie.released_year%></small>
                <small class="text-muted">Rating: <%= @rating %></small>
              </div>
              <%= render 'reviews/form', movie: @movie%>
            </div>
          </div>
        </div>
    <%else%>
      <p>Sorry, Couldnt find any result for your query.</p>
    <%end%>
  </div>
  <% if @reviews.any? %>
    <h5 class="card-title">Reviews: </h5>
    <%= render "reviews/reviews", reviews: @reviews %>
  <% end %>
</div>

app/views/reviews/_form.html.erb
<%= form_with(model: Review.new, method: :post) do |f| %>
  <div class="field form-group">
    <div class="rating">
      <%= f.collection_radio_buttons(:rating, [[5],[4],[3],[2],[1]], :first, :last) do |star| %>
        <%= star.radio_button %>
        <%= star.label(class: "text-white") %>
      <% end %>
    </div>
  </div>
  <div class="field form-group">
    <%=f.label :email, "Your email" %>
    <%=f.text_field :email, class: "form-control", placeholder: "Enter your email"  %>
  </div>
  <div class="field form-group">
    <%= f.label :body, "Leave a review" %>
    <%= f.text_area :description, class: "form-control",
                        placeholder: "Tell people about your experience" %>
  </div>
  <%= f.hidden_field :movie_id, value: movie.id %>
  <div class="actions">
    <%= f.submit "Submit your review", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reviews/_reviews.html.erb
<div class="container-m">
    <div class="row">
        <% reviews.each do |review|%>
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <b>Reviewed by: </b><h5><%= review.email %></h5>
                        </br>
                        </br>
                        <b>Review: </b><p><%= review.description %></p>
                        <b>Rating: </b><p><%= review.rating %></p>
                    </div>
                </div>
            </div>
        <% end %>
    </div>
</div>